version: "3.4"

services:
  superci:
    image: superci
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 1234
        NEXT_PUBLIC_BASE_URL: https://cicd.supri.dev
        NEXT_PUBLIC_GIT_URL: https://git.supri.dev
    environment:
      NODE_ENV: production
      TOKEN: 707f35e44e362069a9fd62e688a12accd80467ae
    ports:
      - 1234:1234
